-- =========================================================
-- Levistro Supabase Database Setup Script
-- Paste this script into Supabase Dashboard -> SQL Editor -> Run
-- =========================================================

-- 1. Create Portfolio Items Table
CREATE TABLE IF NOT EXISTS public.portfolio_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  client TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Web Platforms',
  metric TEXT NOT NULL,
  metricLabel TEXT NOT NULL,
  description TEXT,
  challenge TEXT,
  solution TEXT,
  tags TEXT[] DEFAULT '{}',
  gradient TEXT DEFAULT 'from-blue-600 via-indigo-700 to-slate-900',
  accent TEXT DEFAULT 'text-cyan-400',
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Services Table
CREATE TABLE IF NOT EXISTS public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  tagline TEXT NOT NULL,
  description TEXT NOT NULL,
  iconName TEXT DEFAULT 'Code2',
  features TEXT[] DEFAULT '{}',
  stats TEXT DEFAULT '+100% Growth',
  colSpan TEXT DEFAULT 'lg:col-span-6',
  gradient TEXT DEFAULT 'from-cyan-500/20 via-blue-500/10 to-transparent',
  accentColor TEXT DEFAULT 'text-cyan-400',
  borderColor TEXT DEFAULT 'group-hover:border-cyan-500/40',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- 4. Create Public Read Policies (Allows anyone visiting your website to view cards)
CREATE POLICY "Allow Public Read Portfolio" ON public.portfolio_items
  FOR SELECT USING (true);

CREATE POLICY "Allow Public Read Services" ON public.services
  FOR SELECT USING (true);

-- 5. Create Public Insert/Update/Delete Policies (For Admin Panel access via key)
CREATE POLICY "Allow Public Write Portfolio" ON public.portfolio_items
  FOR ALL USING (true);

CREATE POLICY "Allow Public Write Services" ON public.services
  FOR ALL USING (true);

-- =========================================================
-- Insert Default Starter Seed Data
-- =========================================================

INSERT INTO public.portfolio_items (title, client, category, metric, metricLabel, description, challenge, solution, tags, gradient, accent)
VALUES
  ('Autonomous Fintech Rebrand & Design System', 'Apex Innovations', 'Branding', '+340%', 'Inbound Enterprise Pipeline', 'Complete strategic repositioning, global brand identity, and multi-tier design tokens for a $200M autonomous fintech platform.', 'Apex was perceived as a generic payment gateway rather than an intelligent algorithmic financial operating system.', 'Engineered a monolithic, high-contrast visual system featuring 3D dynamic asset tokens and an executive brand narrative.', ARRAY['Brand Identity', '3D Design Tokens', 'Visual Architecture'], 'from-blue-600 via-indigo-700 to-slate-900', 'text-cyan-400'),
  ('Hyperscale Cloud Platform & Developer Hub', 'Solaria Cloud', 'Web Platforms', '0.38s', 'Global Page Load Time', 'Engineered a lightning-fast web infrastructure and interactive developer documentation with real-time WebGL server telemetry.', 'Complex server analytics led to 65% drop-off in the developer onboarding funnel.', 'Re-architected with Vite, React, and WebGL visualizations, cutting developer onboarding friction by 48%.', ARRAY['React', 'TypeScript', 'WebGL Visuals', 'Tailwind'], 'from-teal-600 via-cyan-800 to-slate-900', 'text-teal-400'),
  ('AI Medical Diagnostics Assistant Interface', 'Vanguard Health', 'AI & Mobile', '99.8%', 'Physician Accuracy Rate', 'Human-centric UI/UX design for real-time generative AI clinical decision support systems deployed across 40+ hospitals.', 'Physicians experienced extreme cognitive overload from dense unorganized raw diagnostic records.', 'Designed an ergonomic clinical workspace with instant AI summaries, confidence scoring chips, and dark-room medical UI.', ARRAY['AI/ML Interface', 'Ergonomic UX', 'Healthcare DS'], 'from-emerald-600 via-teal-800 to-slate-900', 'text-emerald-400');

INSERT INTO public.services (title, tagline, description, iconName, features, stats, colSpan, gradient, accentColor)
VALUES
  ('Brand Strategy & Identity', 'Definitive positioning for global dominance', 'We forge cohesive brand ecosystems from the ground up: corporate identity, design tokens, voice & tone guidelines, and multi-channel asset suites.', 'Palette', ARRAY['Brand Positioning & Narrative', 'Visual Identity & Design Systems', '3D Asset Guidelines', 'Packaging & Collateral'], '+180% Brand Recall', 'lg:col-span-7', 'from-cyan-500/20 via-blue-500/10 to-transparent', 'text-cyan-400'),
  ('Custom Web & Mobile Platforms', 'High-craft engineering with sub-second speeds', 'Bespoke web applications, interactive marketing sites, and high-frequency digital platforms engineered with React, TypeScript, and modern headless architectures.', 'Code2', ARRAY['Full-Stack Cloud Architecture', 'Fluid Micro-Interactions', '99.9% Lighthouse Perf', 'Enterprise Headless CMS'], '0.4s Avg Page Load', 'lg:col-span-5', 'from-teal-500/20 via-emerald-500/10 to-transparent', 'text-teal-400');
